# Generated by Django 4.2.17 on 2025-01-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('count', models.IntegerField()),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
