# Generated by Django 4.2.17 on 2025-01-12 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('conference', 'Конференция'), ('workshop', 'Мастер-класс'), ('seminar', 'Семинар'), ('webinar', 'Вебинар')], default='conference', max_length=50, verbose_name='Тип мероприятия'),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя участника')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='main.event', verbose_name='Мероприятие')),
            ],
        ),
    ]
