# Generated by Django 4.2.17 on 2025-01-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_event_event_type_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='count',
        ),
        migrations.AddField(
            model_name='event',
            name='current_participants',
            field=models.IntegerField(default=0, verbose_name='Количество записавшихся участников'),
        ),
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.IntegerField(default=300, verbose_name='Максимальное количество участников'),
        ),
    ]
