# Generated by Django 4.2.17 on 2025-01-13 06:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_event_count_event_current_participants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='registered_at',
        ),
        migrations.AddField(
            model_name='participant',
            name='birth_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='participant',
            name='course',
            field=models.CharField(default='Не указано', max_length=20),
        ),
        migrations.AddField(
            model_name='participant',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='participant',
            name='faculty',
            field=models.CharField(default='Не указано', max_length=200),
        ),
        migrations.AddField(
            model_name='participant',
            name='full_name',
            field=models.CharField(default='Не указано', max_length=200),
        ),
        migrations.AddField(
            model_name='participant',
            name='gender',
            field=models.CharField(default='Не указано', max_length=10),
        ),
        migrations.AddField(
            model_name='participant',
            name='group',
            field=models.CharField(default='Не указано', max_length=50),
        ),
        migrations.AddField(
            model_name='participant',
            name='phone',
            field=models.CharField(default='Не указано', max_length=20),
        ),
        migrations.AddField(
            model_name='participant',
            name='university',
            field=models.CharField(default='Не указано', max_length=200),
        ),
        migrations.AlterField(
            model_name='participant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='main.event'),
        ),
    ]
